<a href="https://colab.research.google.com/github/CanhForresten/Eksamen/blob/main/Vectors_1_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises for Vectors 1

# Exercise 1

The following code creates some vectors, but when executed it issues an error:

"NameError: name 'np' is not defined"

What could be the cause of it? See slide "Creating  Vectors In NumPy​"...

Correct the code to be able to run it!

In [ ]:
# Insert your correction here

# a vector as a Python list datatype
asList = [1,2,3]

# same numbers, but as a dimensionless numpy array
asArray = np.array([1,2,3])

# again same numbers, but now endowed with orientations
rowVec = np.array([ [1,2,3] ]) # row
colVec = np.array([ [1],[2],[3] ]) # column

# Note the use of spacing when defining the vectors; that is not necessary but makes the code more readable.

# Exercise 2

After correcting the notebook, you will be able to check the shape of the created vectors with the following code.
     

In [ ]:
# Check the sizes of the variables
print(f'asList:  {np.shape(asList)}') # using np's shape function
print(f'asArray: {asArray.shape}') # using a method associated with numpy objects
print(f'rowVec:  {rowVec.shape}')
print(f'colVec:  {colVec.shape}')

Check the API definition of the **type** funtion in Python and call it on asList, asArray, rowVec, and colVec.

In [ ]:
# Your solution here

What is the meaning of the different results?

# Exercise 3
 Create two row vectors u and v, where u contains the elements 2 and 5 and v contains the elements 1 and 3. Create also two column vectors  x and y where x contains elements 3, 4, and 7; and y contains elements 2, 8, and 3.

# Exercise 4
Calculate the following operations:


*   u + v
*   u - v
*   x + y
*   y - x

# Exercise 5
Given a scalar λ = 4. Multiply λ by x.

# Exercise 6


Check the documentation of the function [zeros](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html).

Create a row vector with 5 zeros and a column vector with 2 zeros.

# Exercise 7

Create a new vector vT, that is the vector transpose of vector v.

Create a new vector xT, that is the vector transpose of vector x.

Print all 4 vectors.

In [ ]:
vT =

## Exercise 8

Given vectors a and b defined below:

```
a = np.array([1, 2, 3])
b = np.array([[10],
              [20],
              [30]])
```
when we print their sum

```
print(a+b)
```
We obtain the following array as a result:
```
[[11 12 13]
 [21 22 23]
 [31 32 33]]
```

What is the meaning of this operation? Is this a valid operation of Linear Algebra? You can build your argument from the NumPy [documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html).



# Exercise 9

Calculate the norm of vector w.

In [ ]:
w = np.array([[8],[6],[28]])

# Exercise 10

Create a Python function "toUnit" that will take a vector as input and output a unit vector in the same direction.

Hints:

*   Check how to define functions in this [link](https://www.w3schools.com/python/python_functions.asp)
*   Learn the different arithmetic operators in [here](https://www.w3schools.com/python/gloss_python_arithmetic_operators.asp)


Try your function with vector w. Do not forget to check that the norm of the output vector is indeed 1.

What happens when you input the zeros vector?


## Exercise 11
Given a and b defined below.

Calculate the dot product of a and b.


In [ ]:
a = np.array([[1,2,3]])
b = np.array([[4],[5],[6]])

# Your solution here

# Exercise 12

The dot product is commutative, so if you compute the dot product of b and a you would expect the same result. That is 32.

What happened when you computed the dot product of b and a?

Get a hint on why that happens on the [documentation](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)


Could you solve this issues by using the vector transpose?